console.log(5 > 3 && 3 == 2);
console.log(5 > 3 || 3 == 1);
console.log("______");
console.log(3 == 3 && "Arthur" == "Arthur");
console.log("Arthur" == "Guilherme"|| false);
console.log("______");
console.log(!(true && true));
console.log(!(!(true && true)));
console.log("______");
console.log(true && true);
console.log(false || false);
